// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubactId.Storage.Ef;

#nullable disable

namespace SubactId.Storage.Postgres.Migrations
{
    [DbContext(typeof(SubactIdDbContext))]
    partial class SubactIdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AgentRow", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.PrimitiveCollection<string[]>("AllowedAudiences")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_audiences");

                    b.PrimitiveCollection<string[]>("AllowedScopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_scopes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string[]>("HighRiskAudiences")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("high_risk_audiences");

                    b.Property<string>("Jwks")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("jwks");

                    b.Property<string>("JwksUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("jwks_uri");

                    b.Property<int>("MaxDelegationDepth")
                        .HasColumnType("integer")
                        .HasColumnName("max_delegation_depth");

                    b.Property<TimeSpan>("MaxTaskTtl")
                        .HasColumnType("interval")
                        .HasColumnName("max_task_ttl");

                    b.Property<TimeSpan>("MaxTokenTtl")
                        .HasColumnType("interval")
                        .HasColumnName("max_token_ttl");

                    b.Property<bool>("SponsorRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("sponsor_required");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId")
                        .HasName("pk_agents");

                    b.ToTable("agents", null, t =>
                        {
                            t.HasCheckConstraint("ck_agents_max_delegation_depth", "max_delegation_depth BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AssertionReplayRow", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<string>("Jti")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("AgentId", "Jti")
                        .HasName("pk_assertion_replays");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_assertion_replays_expires_at");

                    b.ToTable("assertion_replays", (string)null);
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AuditArchiveRow", b =>
                {
                    b.Property<DateTimeOffset>("Month")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<byte[]>("Digest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("digest");

                    b.Property<long>("FirstCheckpointId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_checkpoint_id");

                    b.Property<long>("FirstSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("first_seq");

                    b.Property<long>("LastCheckpointId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_checkpoint_id");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seq");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("location");

                    b.Property<string>("Partition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("partition");

                    b.Property<long>("Records")
                        .HasColumnType("bigint")
                        .HasColumnName("records");

                    b.HasKey("Month")
                        .HasName("pk_audit_archives");

                    b.ToTable("audit_archives", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_archives_checkpoints", "first_checkpoint_id >= 1 AND last_checkpoint_id >= first_checkpoint_id - 1");

                            t.HasCheckConstraint("ck_audit_archives_records", "records >= 0");

                            t.HasCheckConstraint("ck_audit_archives_seqs", "first_seq >= 1 AND last_seq >= first_seq - 1");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AuditCheckpointRow", b =>
                {
                    b.Property<long>("CheckpointId")
                        .HasColumnType("bigint")
                        .HasColumnName("checkpoint_id");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long>("FirstSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("first_seq");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kid");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seq");

                    b.Property<byte[]>("PrevCheckpointHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("prev_checkpoint_hash");

                    b.Property<byte[]>("RootHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("root_hash");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<long>("TreeSize")
                        .HasColumnType("bigint")
                        .HasColumnName("tree_size");

                    b.HasKey("CheckpointId")
                        .HasName("pk_audit_checkpoints");

                    b.HasIndex("LastSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_checkpoints_last_seq");

                    b.ToTable("audit_checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_checkpoints_range", "first_seq >= 1 AND first_seq <= last_seq");

                            t.HasCheckConstraint("ck_audit_checkpoints_tree_size", "tree_size >= 1");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AuditEventRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<string>("Audience")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("audience");

                    b.Property<int?>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<string>("Decision")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("decision");

                    b.Property<int?>("DelegationDepth")
                        .HasColumnType("integer")
                        .HasColumnName("delegation_depth");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("detail");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event");

                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Sponsor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor");

                    b.Property<string>("TaskId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("task_id");

                    b.HasKey("Seq", "Ts")
                        .HasName("pk_audit_events");

                    b.HasIndex("Jti")
                        .HasDatabaseName("ix_audit_events_jti");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_audit_events_task_id");

                    b.HasIndex("Ts", "Seq")
                        .HasDatabaseName("ix_audit_events_ts_seq");

                    b.HasIndex(new[] { "Ts", "Seq" }, "ix_audit_events_deny_ts_seq")
                        .HasDatabaseName("ix_audit_events_deny_ts_seq")
                        .HasFilter("decision = 'deny'");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_decision", "decision IS NULL OR decision IN ('allow', 'deny')");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AuditOutboxRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("AuditSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("audit_seq");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_outbox");

                    b.HasIndex("AuditSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_outbox_audit_seq");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_audit_outbox_next_attempt_at");

                    b.ToTable("audit_outbox", (string)null);
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.RevocationRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("IssuedBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_before");

                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("revoked_by");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("session_id");

                    b.Property<string>("SponsorKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_key");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<string>("TaskId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_revocations");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_revocations_agent_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_revocations_expires_at")
                        .HasFilter("jti IS NOT NULL");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("ix_revocations_jti")
                        .HasFilter("jti IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_revocations_session_id");

                    b.HasIndex("SponsorKey")
                        .HasDatabaseName("ix_revocations_sponsor_key");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_revocations_subject");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_revocations_task_id");

                    b.HasIndex(new[] { "RevokedAt" }, "ix_revocations_sign_outs_revoked_at")
                        .HasDatabaseName("ix_revocations_sign_outs_revoked_at")
                        .HasFilter("session_id IS NOT NULL OR issued_before IS NOT NULL");

                    b.ToTable("revocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_revocations_target", "jti IS NOT NULL OR task_id IS NOT NULL OR agent_id IS NOT NULL OR sponsor_key IS NOT NULL OR session_id IS NOT NULL OR subject IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.ScimUserRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("SponsorKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_scim_users");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_scim_users_external_id");

                    b.HasIndex("SponsorKey")
                        .HasDatabaseName("ix_scim_users_sponsor_key");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_scim_users_user_name");

                    b.ToTable("scim_users", (string)null);
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.SignalReplayRow", b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<string>("Jti")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("Issuer", "Jti")
                        .HasName("pk_signal_replays");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_signal_replays_expires_at");

                    b.ToTable("signal_replays", (string)null);
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.SignalWatermarkRow", b =>
                {
                    b.Property<string>("SponsorKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_key");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at");

                    b.HasKey("SponsorKey")
                        .HasName("pk_ssf_signal_watermarks");

                    b.ToTable("ssf_signal_watermarks", (string)null);
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.SponsorBlockRow", b =>
                {
                    b.Property<string>("SponsorKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_key");

                    b.Property<DateTimeOffset>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<bool>("PlacedByDeletion")
                        .HasColumnType("boolean")
                        .HasColumnName("placed_by_deletion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("SponsorKey")
                        .HasName("pk_sponsor_blocks");

                    b.ToTable("sponsor_blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_sponsor_blocks_kind", "kind IN ('disabled', 'deleted')");

                            t.HasCheckConstraint("ck_sponsor_blocks_source", "source IN ('admin', 'poll', 'logout', 'scim', 'ssf')");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.TaskGrantRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("GrantHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("grant_hash");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("Renewals")
                        .HasColumnType("integer")
                        .HasColumnName("renewals");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_grants");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_task_grants_agent_id");

                    b.HasIndex("GrantHash")
                        .IsUnique()
                        .HasDatabaseName("ix_task_grants_grant_hash");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_grants_task_id");

                    b.ToTable("task_grants", (string)null);
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.TaskRow", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("task_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("audience");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DelegationDepth")
                        .HasColumnType("integer")
                        .HasColumnName("delegation_depth");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ParentTaskId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parent_task_id");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("session_id");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor");

                    b.Property<string>("SponsorKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("TaskId")
                        .HasName("pk_tasks");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_tasks_agent_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_tasks_expires_at")
                        .HasFilter("status = 'active'");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("ix_tasks_parent_task_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tasks_session_id");

                    b.HasIndex("Sponsor")
                        .HasDatabaseName("ix_tasks_sponsor");

                    b.HasIndex("SponsorKey")
                        .HasDatabaseName("ix_tasks_sponsor_key");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_delegation_depth", "delegation_depth >= 1");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('active', 'expired', 'revoked')");
                        });
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.AssertionReplayRow", b =>
                {
                    b.HasOne("SubactId.Storage.Ef.Schema.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assertion_replays_agents_agent_id");
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.TaskGrantRow", b =>
                {
                    b.HasOne("SubactId.Storage.Ef.Schema.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_grants_agents_agent_id");

                    b.HasOne("SubactId.Storage.Ef.Schema.TaskRow", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_grants_tasks_task_id");
                });

            modelBuilder.Entity("SubactId.Storage.Ef.Schema.TaskRow", b =>
                {
                    b.HasOne("SubactId.Storage.Ef.Schema.AgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_agents_agent_id");

                    b.HasOne("SubactId.Storage.Ef.Schema.TaskRow", null)
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_tasks_parent_task_id");
                });
#pragma warning restore 612, 618
        }
    }
}
