#!/usr/bin/env bash
# Brings the sizing rig up, down, or back to an empty database.
#
# The signing key, admin API key and database passwords are generated into ./.secrets and ./.env,
# which git ignores.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

secrets="$here/.secrets"
envfile="$here/.env"

usage() {
  cat >&2 <<'EOF'
usage: rig.sh <command>

  secrets   generate the signing key and the passwords, if they are not there already
  build     build the control plane image from the repository Dockerfile, and the rig's own
  up        bring the rig up and wait for the control plane to report ready
  down      stop the rig, keeping the database
  reset     stop the rig and delete the database volume, so the next up starts empty
  ps        what is running

To measure a machine that is not also generating the load, export RIG_ADDRESS (an address of
this host the generator can reach), RIG_BIND (the address to publish the rig's ports on, usually
the same one) and BENCH_DOCKER_HOST (the generator's Docker endpoint) before build and up.
EOF
  exit 2
}

make_secrets() {
  mkdir -p "$secrets"
  chmod 700 "$secrets"

  if [ ! -f "$secrets/signing-key.pem" ]; then
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$secrets/signing-key.pem" >/dev/null 2>&1
    # Readable by the container's non-root user.
    chmod 644 "$secrets/signing-key.pem"
    echo "made a signing key"
  fi

  if [ ! -f "$envfile" ]; then
    {
      echo "# Generated by rig.sh. Not for anything but this rig, and not in the repository."
      echo "SUBACTID_ADMIN_API_KEY=$(openssl rand -hex 32)"
      echo "POSTGRES_PASSWORD=$(openssl rand -hex 16)"
      echo "POSTGRES_SUPERUSER_PASSWORD=$(openssl rand -hex 16)"
      echo "KEYCLOAK_ADMIN_PASSWORD=$(openssl rand -hex 16)"
    } > "$envfile"
    chmod 600 "$envfile"
    echo "made $envfile"
  fi
}

case "${1:-}" in
  secrets)
    make_secrets
    ;;

  build)
    make_secrets
    # Optional CA for networks with a TLS-intercepting proxy: set BUILD_CA_FILE to the PEM.
    ca=()
    if [ -n "${BUILD_CA_FILE:-}" ]; then
      ca=(--secret "id=build_ca,src=$BUILD_CA_FILE")
    fi

    # The control plane is built from the release Dockerfile. With BUILD_CA_FILE set, a temporary
    # copy trusts the CA before the restore. The runtime stage is unchanged.
    server_dockerfile="$here/../Dockerfile"
    if [ -n "${BUILD_CA_FILE:-}" ]; then
      server_dockerfile="$(mktemp)"
      trap 'rm -f "$server_dockerfile"' EXIT
      awk '
        /^RUN dotnet restore / && !done {
          print "RUN --mount=type=secret,id=build_ca,target=/tmp/build-ca.crt \\"
          print "    cp /tmp/build-ca.crt /usr/local/share/ca-certificates/build-proxy.crt && update-ca-certificates"
          done = 1
        }
        { print }
      ' "$here/../Dockerfile" > "$server_dockerfile"
    fi
    docker build "${ca[@]+"${ca[@]}"}" -f "$server_dockerfile" --target server -t subactid-bench/control-plane:local "$here/.."
    docker build "${ca[@]+"${ca[@]}"}" -f "$here/keycloak/Dockerfile" -t subactid-bench/keycloak:26.7.4 "$here/keycloak"
    docker build "${ca[@]+"${ca[@]}"}" -f "$here/SubactId.Bench/Dockerfile" -t subactid-bench/load-generator:local "$here/.."

    # Build the load generator on the remote machine too, sending the context from here.
    if [ -n "${BENCH_DOCKER_HOST:-}" ]; then
      echo "building the load generator on $BENCH_DOCKER_HOST"
      docker -H "$BENCH_DOCKER_HOST" build "${ca[@]+"${ca[@]}"}" \
        -f "$here/SubactId.Bench/Dockerfile" -t subactid-bench/load-generator:local "$here/.."
    fi
    ;;

  up)
    make_secrets
    docker compose up -d postgres keycloak subactid
    echo "waiting for the control plane to report ready"
    for _ in $(seq 1 180); do
      if curl -fsS "http://${RIG_BIND:-127.0.0.1}:5100/readyz" >/dev/null 2>&1; then
        echo "ready"
        exit 0
      fi
      sleep 2
    done
    echo "the control plane never became ready" >&2
    docker compose logs --tail 50 subactid >&2
    exit 1
    ;;

  down)
    docker compose down
    ;;

  reset)
    docker compose down -v
    ;;

  ps)
    docker compose ps
    ;;

  *)
    usage
    ;;
esac
